version: "3.7"

services:
  esp-idf:
    build:
      context: . 
      dockerfile: Dockerfiles/Dockerfile.esp-idf
      args:
        ESP_IDF_VERSION: ${ESP_IDF_VERSION}
        TARGET: ${TARGET}        
    image: build
    container_name: build_project
    environment:
      ESP_IDF_VERSION: ${ESP_IDF_VERSION}
      TARGET: ${TARGET}
    command:     
      - "idf.py build flash"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    volumes:
      - ${PWD}/:/app
  runner:
    build:
      context: .
      dockerfile: ./Dockerfiles/Dockerfile.runner
      args:
        GITHUB_RUNNER_VERSION: ${GITHUB_RUNNER_VERSION}
        RUNNER_NAME: ${RUNNER_NAME}       
        GITHUB_REPO_NAME: ${GITHUB_REPO_NAME} 
        RUNNER_REPOSITORY_URL: ${RUNNER_REPOSITORY_URL}
        GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
        RUNNER_LABELS: ${RUNNER_LABELS}

    image: runner:v0.0.1
    container_name: runner
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
