version: "3.7"

services:
  esp-idf:
    build:
      context: . 
      dockerfile: Dockerfiles/Dockerfile.esp-idf
      args:
        ESP_IDF_VERSION: ${ESP_IDF_VERSION}
        TARGET: ${TARGET}        
    image: build
    container_name: build_project
    environment:
      ESP_IDF_VERSION: ${ESP_IDF_VERSION}
      TARGET: ${TARGET}
    command:     
      - "idf.py build flash"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    volumes:
      - ${PWD}/:/app
  runner:
    build:
      context: .
      dockerfile: Dockerfile.runner
      args:
        RUNNER_NAME: ${RUNNER_NAME}
        WORKDIR: ${WORKDIR}
        GITHUB_RUNNER_VERSION: ${GITHUB_RUNNER_VERSION}
        RUNNER_REPOSITORY_URL: ${RUNNER_REPOSITORY_URL}
        GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
    image: runner:v0.0.2
    container_name: runner
    environment:
      RUNNER_NAME: ${RUNNER_NAME}
      WORKDIR: ${WORKDIR}
      GITHUB_RUNNER_VERSION: ${GITHUB_RUNNER_VERSION}
      RUNNER_REPOSITORY_URL: ${RUNNER_REPOSITORY_URL}
      GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
