name: Build and Push to Docker-hub

env:
  ESP_IDF_VERSION: V5.0.1

on:
  push:
    paths:
    - 'Dockerfiles/*'
    
jobs:
  build_and_push:
    runs-on: ubuntu-20.04
    name: build and push image to docker-hub
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2   
           
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}           
      
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: .
          dockerfile: ./Dockerfiles/Dockerfile.esp-idf        
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:${{ env.ESP_IDF_VERSION }}
