name: Build and Push to Docker-hub

on:
  push:
    paths:
    - 'Dockerfiles/*'
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-20.04
    name: build and push image to docker-hub
    env:
      ESP_IDF_VERSION: v5.0.1
      TARGET: esp32
      GITHUB_RUNNER_VERSION: 2.302.1
      RUNNER_REPOSITORY_URL: https://github.com/${{ github.repository }}      
      RUNNER_NAME: "Runner-build"
      RUNNER_LABELS: "Runner-Build"      
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_TOKEN }}
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2   
           
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}   

      - name: Build and push ESP-IDF to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: ./Dockerfiles
          file: ./Dockerfiles/Dockerfile.esp-idf
          build-args: |
            ESP_IDF_VERSION=${{ env.ESP_IDF_VERSION }}
            TARGET=${{ env.TARGET }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/esp-idf:${{ env.ESP_IDF_VERSION }}
      - name: Build and push Runner-Self-Hosted to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: ./Dockerfiles
          file: ./Dockerfiles/Dockerfile.runner
          build-args: |
            GITHUB_RUNNER_VERSION=${{ env.GITHUB_RUNNER_VERSION }}
            RUNNER_REPOSITORY_URL=${{ env.RUNNER_REPOSITORY_URL }}
            GITHUB_OWNER=${{ github.repository_owner }}           
            GITHUB_REPO=${{ github.repository#*/ }}
            RUNNER_NAME=${{ env.RUNNER_NAME }}
            WORKDIR=${{ github.repository }}
            RUNNER_LABELS=${{ env.RUNNER_LABELS }}     
            GITHUB_ACCESS_TOKEN=${{ secrets.GITHUB_ACCESS_TOKEN }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/runner:${{ env.GITHUB_RUNNER_VERSION }}
