name: Build, Test and Upload to Board

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths:
      - 'src/*'
      - 'include/*'
      - 'test/*'
  #pull_request:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: "Build-Test-Upload"
    runs-on: self-hosted    
    steps:    
      - name: Checkout
        uses: actions/checkout@v3
      - name: Compile project
        run: |
          get_idf && idf.py build
          